### PR TITLE
Fix issue with multiple binaries getting returned from tfsec releases

### LINKED ISSUE #8: Action fails to download tfsec
Hi there 👋 

I noticed there were a few [tfsec releases](https://github.com/tfsec/tfsec/releases) in the last 24 hours which broke this action as some extra binaries were introduced.

The result of:

```bash
wget -q https://api.github.com/repos/liamg/tfsec/releases/latest -O - | grep -o -E "https://.+?-linux-amd64"
```

now yields:

```bash
https://github.com/tfsec/tfsec/releases/download/v0.32.1/tfsec-checkgen-linux-amd64
https://github.com/tfsec/tfsec/releases/download/v0.32.1/tfsec-linux-amd64
```

So it fails to download into a tfsec binary. I'll raise a PR request shortly for the fix.

### PR DESCRIPTION
**Pull request by paul-pop**
Fixes #8

### CODE REVIEW

**Review by rikhilrai — APPROVED** [review]

**Comment by paul-pop** [comment]
@Vlaaaaaaad would appreciate a merge if you're around :)

**Comment by Vlaaaaaaad** [comment]
Tested the two `wget` commands and your line indeed downloads the right binary.

Merging as I see that as enough testing

**Review by Vlaaaaaaad — APPROVED** [review]

**Comment by review-dog** [comment]
Hi, @paul-pop! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintainance of reviewdog.

Thanks again!

**Comment by paul-pop** [comment]
Thank you @Vlaaaaaaad appreciate the quick review! 🚀

**Pull request merged**
